In [52]:
import numpy as np
import tensorflow as tf
import pickle
import sys
import pandas as pd

In [53]:
#train_data = pd.read_pickle("../dataset/train.pickle")

In [54]:
test_data = pd.read_pickle("../dataset/test.pickle")

In [59]:
with pd.option_context('display.max_rows', None):
    display(test_data.head(1000))

0  CWE-119  CWE-120  \
0    default_event_handler( \n    GuiWidget *widget...    False    False   
1    krb5_krbhst_init_flags(krb5_context context,\n...    False    False   
2    swap_info_get(swp_entry_t entry)\n{\n\tstruct ...    False    False   
3    parseattribs4(char *&c, const Vec4 &ival = Vec...    False    False   
4    generateExecCode(CompileState* comp)\n{\n    g...    False    False   
5    use_vfp_abi (enum arm_pcs pcs_variant, bool is...    False    False   
6    hasUsesToReplace(GlobalAlias &GA, const LLVMUs...    False    False   
7    load_tile_set( const char *set ) {\n  string s...    False    False   
8    BufFileSeek(BufFile *file, int fileno, long of...    False    False   
9    sendPlayPacket(rtmp::RTMP& r, FakeNC& nc)\n{\n...    False    False   
10   buildToken( char *text )\n#else\nbuildToken( t...    False    False   
11   putcharacter(scheme *sc, int c) {\n  port *pt=...    False    False   
12   mtk_i2c_init_hw(struct mtk_i2c *i2c)\n{\n\tu16...    False    False   
13   check_conversion(const char *s, const char *ep...    False    False   
14   isLoopInvariant(const Value *V) const {\n  if ...    False    False   
15   efi_image_probe ( struct image *image ) {\n\tE...    False    False   
16   raid1_spare_active(struct mddev *mddev)\n{\n\t...    False    False   
17   httpSetRoutePathVar(HttpRoute *route, cchar *k...    False    False   
18   clutter_gdk_set_display (GdkDisplay *display)\...    False    False   
19   TTYtoVT(const char *tty)\n{\n    if (!memcmp(t...    False    False   
20   gdip_region_bitmap_union (GpRegionBitmap *shap...    False    False   
21   ParseCSVResponse(char* pszLine,\n             ...    False    False   
22   Next()\n{\n   Real ak,y; int ir1;\n   if (NotR...    False    False   
23   upper_layer_chksum_ipv4(struct uip_stack *usta...    False    False   
24   find(FXint fd) {\n    FXMutexLock lock(mutex);...    False    False   
25   CreateCategory(\n\tCategory_Struct *& category...    False    False   
26   egg_asn1x_set_oid_as_quark (GNode *node,\n    ...    False    False   
27   saveParzenPDFToTextFile(\n\tconst char\t*fileN...    False    False   
28   cup_winselect_init(void)\n{\n\tint i = 0;\n\ti...    False    False   
29   opera1_usb_i2c_msgxfer(struct dvb_usb_device *...    False    False   
30   initGISTstate(GISTSTATE *giststate, Relation i...    False    False   
31   mapstep(const struct tile *ptile, enum directi...    False    False   
32   savagefb_delete_i2c_busses(struct fb_info *inf...    False    False   
33   cleanup_cap_releases(struct ceph_mds_client *m...    False    False   
34   be_wrb_hdr_prepare(struct be_mcc_wrb *wrb, int...    False    False   
35   ValidateEnumOptions(EnumDescriptor* enm,\n    ...    False    False   
36   __perf_event_header_size(struct perf_event *ev...    False    False   
37   update_active_workspace (WnckScreen *screen)\n...    False    False   
38   generate_subquery_vars(List *tlist, Index varn...    False    False   
39   setmark_pos(c, pos, fnum)\n    int\t\tc;\n    ...    False    False   
40   common_select_close()\n{\n\tif ( !Common_selec...    False    False   
41   cleanup()\n{\n    if (file != NULL)\n\tfclose(...    False    False   
42   xmlrpc_client_call_server_asynch_params(\n    ...    False    False   
43   sst_send_byte_stream(struct device *dev,\n\t\t...    False    False   
44   DeleteBaseReg(const SCEV *&S) {\n  if (&S != &...    False    False   
45   vertex_dfs_finishing_time (Vertex * vertex, in...    False    False   
46   skype_initiate_chat(PurpleBlistNode *node, gpo...    False    False   
47   SHLD_EwGwR(bxInstruction_c *i)\n{\n  Bit16u op...    False    False   
48   ipa_tm_scan_calls_clone (struct cgraph_node *n...    False    False   
49   vfp_vep_callback(const struct sess *sp, ssize_...     True     True   
50   destroy_loop_vec_info (loop_vec_info loop_vinf...    False    False   
51   xml_open_file(const gchar *path)\n{\n\tXMLFile...    False    False   
52   Exp_MatchMaxObjCmd(\

In [56]:
# The paper does not declare the num of words to track, I am using 10000 here

#tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10000)

# Required before using texts_to_sequences
# Arguments; a list of strings

#tokenizer.fit_on_texts(list(train_data[0]))

In [57]:
#with open ('../tokenizer/tokenizer.pickle', 'wb') as handle:
#    pickle.dump(tokenizer, handle, protocol=4)

In [58]:
with open('../tokenizer/tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

## Test dataset 10

In [8]:
test_data.loc[[10]][0]

10    buildToken( char *text )\n#else\nbuildToken( t...
Name: 0, dtype: object

In [9]:
with pd.option_context('display.max_colwidth', None):
    display(test_data.loc[[10]][0])

10    buildToken( char *text )\n#else\nbuildToken( text )\nchar *text;\n#endif\n{\n\tJunction *j1, *j2;\n\tGraph g;\n\tTokNode *t;\n\trequire(text!=NULL, "buildToken: invalid token name");\n\t\n\tj1 = newJunction();\n\tj2 = newJunction();\n\tt = newTokNode();\n\tt->altstart = CurAltStart;\n\tif ( *text == '"' ) {t->label=FALSE; t->token = addTexpr( text );}\n\telse {t->label=TRUE; t->token = addTname( text );}\n\tj1->p1 = (Node *) t;\n\tt->next = (Node *) j2;\n\tg.left = (Node *) j1; g.right = (Node *) j2;\n\treturn g;\n}
Name: 0, dtype: object

In [10]:
y_test_10 = test_data.loc[[10]][test_data.columns[1:]].astype(int)
y_test_10

CWE-119  CWE-120  CWE-469  CWE-476  CWE-other
10        0        0        0        1          0

In [11]:
test_tokenized_10 = tokenizer.texts_to_sequences(test_data.loc[[10]][0])

In [12]:
x_test_10 = tf.keras.preprocessing.sequence.pad_sequences(test_tokenized_10, maxlen=500, padding="post")

## Test dataset 17

In [13]:
test_data.loc[[17]][0]

17    httpSetRoutePathVar(HttpRoute *route, cchar *k...
Name: 0, dtype: object

In [14]:
with pd.option_context('display.max_colwidth', None):
    display(test_data.loc[[17]][0])

17    httpSetRoutePathVar(HttpRoute *route, cchar *key, cchar *value)\n{\n    mprAssert(route);\n    mprAssert(key);\n    mprAssert(value);\n\n    GRADUATE_HASH(route, pathTokens);\n    if (schr(value, '$')) {\n        value = stemplate(value, route->pathTokens);\n    }\n    mprAddKey(route->pathTokens, key, sclone(value));\n}
Name: 0, dtype: object

In [15]:
df_temp = pd.DataFrame({'source_code':[]})
with open('test_17.txt', 'r') as file:
    line = file.readline()
    df_temp = df_temp.append({'source_code':line}, ignore_index=True)

In [16]:
df_temp.loc[0]

source_code    httpSetRoutePathVar(HttpRoute *route, cchar *k...
Name: 0, dtype: object

In [17]:
y_test_17 = test_data.loc[[17]][test_data.columns[1:]].astype(int)
y_test_17

CWE-119  CWE-120  CWE-469  CWE-476  CWE-other
17        0        0        0        1          0

In [18]:
test_tokenized_17 = tokenizer.texts_to_sequences(test_data.loc[[17]][0])

In [19]:
x_test_17 = tf.keras.preprocessing.sequence.pad_sequences(test_tokenized_17, maxlen=500, padding="post")

## Test dataset 49

In [20]:
test_data.loc[[49]][0]

49    vfp_vep_callback(const struct sess *sp, ssize_...
Name: 0, dtype: object

In [21]:
with pd.option_context('display.max_colwidth', None):
    display(test_data.loc[[49]][0])

49    vfp_vep_callback(const struct sess *sp, ssize_t l, enum vgz_flag flg)\n{\n\tstruct vef_priv *vef;\n\tsize_t dl, px;\n\tconst void *dp;\n\tint i;\n\n\tCHECK_OBJ_NOTNULL(sp, SESS_MAGIC);\n\tvef = sp->wrk->vef_priv;\n\tCHECK_OBJ_NOTNULL(vef, VEF_MAGIC);\n\tassert(l >= 0);\n\n\tif (vef->error) {\n\t\tvef->tot += l;\n\t\treturn (vef->tot);\n\t}\n\n\t/*\n\t * l == 0 is valid when 'flg' calls for action, but in the\n\t * normal case we can just ignore a l==0 request.\n\t * (It would cause Z_BUF_ERROR anyway)\n\t */\n\tif (l == 0 && flg == VGZ_NORMAL)\n\t\treturn (vef->tot);\n\n\tdo {\n\t\tpx = vef->npend;\n\t\tif (l < px)\n\t\t\tpx = l;\n\t\tif (px != 0) {\n\t\t\tVGZ_Ibuf(vef->vgz, vef->pending, px);\n\t\t\tl -= px;\n\t\t} else {\n\t\t\tVGZ_Ibuf(vef->vgz, vef->bufp, l);\n\t\t\tvef->bufp += l;\n\t\t\tl = 0;\n\t\t}\n\t\tdo {\n\t\t\tif (VGZ_ObufStorage(sp, vef->vgz)) {\n\t\t\t\tvef->error = errno;\n\t\t\t\tvef->tot += l;\n\t\t\t\treturn (vef->tot);\n\t\t\t}\n\t\t\ti = VGZ_Gzip(vef->vgz, &d

In [22]:
y_test_49 = test_data.loc[[49]][test_data.columns[1:]].astype(int)
y_test_49

CWE-119  CWE-120  CWE-469  CWE-476  CWE-other
49        1        1        0        0          0

In [23]:
test_tokenized_49 = tokenizer.texts_to_sequences(test_data.loc[[49]][0])

In [24]:
x_test_49 = tf.keras.preprocessing.sequence.pad_sequences(test_tokenized_49, maxlen=500, padding="post")

In [25]:
y_test_binary_49 = (test_data.loc[[49]][test_data.columns[1:]]).any(axis=1, bool_only=bool).astype(int)
y_test_binary_49

49    1
dtype: int32

## Test dataset 108

In [61]:
test_data.loc[108][0]

'eb_jabber_read_prefs_config(LList *values)\n{\n\tchar *c;\n\tc = value_pair_get_value(values, "server");\n\n\tif (c) {\n\t\tstrcpy(jabber_server, c);\n\t\tfree(c);\n\t}\n\tc = value_pair_get_value(values, "do_jabber_debug");\n\tif (c) {\n\t\tdo_jabber_debug = atoi(c);\n\t\tfree(c);\n\t}\n}'

In [62]:
with pd.option_context('display.max_colwidth', None):
    display(test_data.loc[[108]][0])

108    eb_jabber_read_prefs_config(LList *values)\n{\n\tchar *c;\n\tc = value_pair_get_value(values, "server");\n\n\tif (c) {\n\t\tstrcpy(jabber_server, c);\n\t\tfree(c);\n\t}\n\tc = value_pair_get_value(values, "do_jabber_debug");\n\tif (c) {\n\t\tdo_jabber_debug = atoi(c);\n\t\tfree(c);\n\t}\n}
Name: 0, dtype: object

In [63]:
y_test_108 = test_data.loc[[108]][test_data.columns[1:]].astype(int)
y_test_108

CWE-119  CWE-120  CWE-469  CWE-476  CWE-other
108        1        1        0        0          1

In [64]:
test_tokenized_108 = tokenizer.texts_to_sequences(test_data.loc[[108]][0])

In [65]:
x_test_108 = tf.keras.preprocessing.sequence.pad_sequences(test_tokenized_108, maxlen=500, padding="post")

In [66]:
y_test_binary_108 = (test_data.loc[[108]][test_data.columns[1:]]).any(axis=1, bool_only=bool).astype(int)
y_test_binary_108

108    1
dtype: int32

## Binary Model

In [26]:
binary_model = tf.keras.models.load_model('../trained_model/Simple_CNN_binary')

In [27]:
binary_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 13)           130000    
_________________________________________________________________
conv1d (Conv1D)              (None, 492, 512)          60416     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 123, 512)          0         
_________________________________________________________________
dropout (Dropout)            (None, 123, 512)          0         
_________________________________________________________________
flatten (Flatten)            (None, 62976)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                4030528   
_________________________________________________________________
dense_1 (Dense)              (None, 16)                1

## Prediction for Test data 17

In [28]:
binary_model.predict(x_test_17)

array([[0.883872]], dtype=float32)

In [29]:
y_test_binary_17 = (test_data.loc[[17]][test_data.columns[1:]]).any(axis=1, bool_only=bool).astype(int)
y_test_binary_17

17    1
dtype: int32

In [30]:
binary_model.evaluate(x_test_17, y_test_binary_17)

1/1 [==============================] - 0s 979us/step - loss: 0.1234 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.1234431117773056, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]

## Prediction for Test data 49

In [31]:
binary_model.predict(x_test_49)

array([[0.9966521]], dtype=float32)

In [32]:
y_test_binary_49 = (test_data.loc[[49]][test_data.columns[1:]]).any(axis=1, bool_only=bool).astype(int)
y_test_binary_49

49    1
dtype: int32

In [33]:
binary_model.evaluate(x_test_49, y_test_binary_49)

1/1 [==============================] - 0s 2ms/step - loss: 0.0034 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.0033534662798047066, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]

## Prediction for Test data 10

In [34]:
binary_model.predict(x_test_10)

array([[0.7742851]], dtype=float32)

In [35]:
y_test_binary_10 = (test_data.loc[[10]][test_data.columns[1:]]).any(axis=1, bool_only=bool).astype(int)
y_test_binary_10

10    1
dtype: int32

In [36]:
binary_model.evaluate(x_test_10, y_test_binary_10)

1/1 [==============================] - 0s 2ms/step - loss: 0.2558 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.25581517815589905, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]

## Prediction for Test data 108

In [67]:
binary_model.predict(x_test_108)

array([[0.849997]], dtype=float32)

In [68]:
y_test_binary_108 = (test_data.loc[[108]][test_data.columns[1:]]).any(axis=1, bool_only=bool).astype(int)
y_test_binary_108

108    1
dtype: int32

In [69]:
binary_model.evaluate(x_test_108, y_test_binary_108)

1/1 [==============================] - 0s 2ms/step - loss: 0.1625 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.16252250969409943, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]

## CWE119 Model

In [37]:
CWE119_model = tf.keras.models.load_model('../trained_model/Simple_CNN_CWE119')

In [38]:
CWE119_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 13)           130000    
_________________________________________________________________
conv1d (Conv1D)              (None, 492, 512)          60416     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 123, 512)          0         
_________________________________________________________________
dropout (Dropout)            (None, 123, 512)          0         
_________________________________________________________________
flatten (Flatten)            (None, 62976)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                4030528   
_________________________________________________________________
dense_1 (Dense)              (None, 16)                1

## Prediction for Test data 49

In [39]:
CWE119_model.predict(x_test_49)

array([[0.0013935]], dtype=float32)

In [40]:
y_test_CWE119_49 = (test_data.loc[[49]][test_data.columns[1]]).astype(int)
y_test_CWE119_49

49    1
Name: CWE-119, dtype: int32

In [41]:
CWE119_model.evaluate(x_test_49, y_test_CWE119_49)

1/1 [==============================] - 0s 944us/step - loss: 6.5759 - tp: 0.0000e+00 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 1.0000 - accuracy: 0.0000e+00 - precision: 0.0000e+00 - recall: 0.0000e+00 - auc: 0.0000e+00


[6.575931072235107, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]

## Prediction for Test data 108

In [70]:
CWE119_model.predict(x_test_108)

array([[0.24892616]], dtype=float32)

In [71]:
y_test_CWE119_108 = (test_data.loc[[108]][test_data.columns[1]]).astype(int)
y_test_CWE119_108

108    1
Name: CWE-119, dtype: int32

In [72]:
CWE119_model.evaluate(x_test_108, y_test_CWE119_108)

1/1 [==============================] - 0s 2ms/step - loss: 1.3906 - tp: 0.0000e+00 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 1.0000 - accuracy: 0.0000e+00 - precision: 0.0000e+00 - recall: 0.0000e+00 - auc: 0.0000e+00


[1.3905988931655884, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]

## CWE120 Model

In [42]:
CWE120_model = tf.keras.models.load_model('../trained_model/Simple_CNN_CWE120')

In [43]:
CWE120_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 13)           130000    
_________________________________________________________________
conv1d (Conv1D)              (None, 492, 512)          60416     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 123, 512)          0         
_________________________________________________________________
dropout (Dropout)            (None, 123, 512)          0         
_________________________________________________________________
flatten (Flatten)            (None, 62976)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                4030528   
_________________________________________________________________
dense_1 (Dense)              (None, 16)                1

## Prediction for Test data 49

In [44]:
CWE120_model.predict(x_test_49)

array([[0.03866386]], dtype=float32)

In [45]:
y_test_CWE120_49 = (test_data.loc[[49]][test_data.columns[2]]).astype(int)
y_test_CWE120_49

49    1
Name: CWE-120, dtype: int32

In [46]:
CWE120_model.evaluate(x_test_49, y_test_CWE120_49)

1/1 [==============================] - 0s 2ms/step - loss: 3.2528 - tp: 0.0000e+00 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 1.0000 - accuracy: 0.0000e+00 - precision: 0.0000e+00 - recall: 0.0000e+00 - auc: 0.0000e+00


[3.2528493404388428, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]

## Prediction for Test data 108

In [73]:
CWE120_model.predict(x_test_108)

array([[0.9274756]], dtype=float32)

In [74]:
y_test_CWE120_108 = (test_data.loc[[108]][test_data.columns[2]]).astype(int)
y_test_CWE120_108

108    1
Name: CWE-120, dtype: int32

In [75]:
CWE120_model.evaluate(x_test_108, y_test_CWE120_108)

1/1 [==============================] - 0s 2ms/step - loss: 0.0753 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.0752888172864914, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]

## CWE476 Model

In [47]:
CWE476_model = tf.keras.models.load_model('../trained_model/Simple_CNN_CWE476')

In [48]:
CWE476_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 13)           130000    
_________________________________________________________________
conv1d (Conv1D)              (None, 492, 512)          60416     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 123, 512)          0         
_________________________________________________________________
dropout (Dropout)            (None, 123, 512)          0         
_________________________________________________________________
flatten (Flatten)            (None, 62976)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                4030528   
_________________________________________________________________
dense_1 (Dense)              (None, 16)                1

In [49]:
CWE476_model.predict(x_test_17)

array([[0.9881383]], dtype=float32)

In [50]:
y_test_CWE476_17 = (test_data.loc[[17]][test_data.columns[4]]).astype(int)
y_test_CWE476_17

17    1
Name: CWE-476, dtype: int32

In [51]:
CWE476_model.evaluate(x_test_17, y_test_CWE476_17)

1/1 [==============================] - 0s 976us/step - loss: 0.0119 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.011932579800486565, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]

## CWE-others Model

In [78]:
others_model = tf.keras.models.load_model('../trained_model/Simple_CNN_CWE-others')

In [79]:
others_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 500, 13)           130000    
_________________________________________________________________
conv1d (Conv1D)              (None, 492, 512)          60416     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 123, 512)          0         
_________________________________________________________________
dropout (Dropout)            (None, 123, 512)          0         
_________________________________________________________________
flatten (Flatten)            (None, 62976)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                4030528   
_________________________________________________________________
dense_1 (Dense)              (None, 16)                1

In [80]:
others_model.predict(x_test_108)

array([[0.91732275]], dtype=float32)

In [81]:
y_test_others_108 = (test_data.loc[[108]][test_data.columns[5]]).astype(int)
y_test_others_108

108    1
Name: CWE-other, dtype: int32

In [83]:
others_model.evaluate(x_test_108, y_test_others_108)

1/1 [==============================] - 0s 996us/step - loss: 0.0863 - tp: 1.0000 - fp: 0.0000e+00 - tn: 0.0000e+00 - fn: 0.0000e+00 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - auc: 0.0000e+00


[0.08629582822322845, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0]